name = "planner"
main = "planner-worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
MS_CLIENT_ID = "14d82eec-204b-4c2f-b7e8-296a70dab67e"
VAPID_PUBLIC_KEY = "BO9e7WsKYMLszuLrzWdfuDcSeYlwSGLQT5D0JTQKJLBP904-2gKHY_uw1VglWKNC6B4c2eRCZPWRC2tIpK6wxbY"
REMINDER_EMAIL_TO = "kandyphoenix@hotmail.com"

[[kv_namespaces]]
binding = "PLANNER_KV"
id = "706d09105d8148cc802b9ce349ca7460"

[triggers]
crons = ["0 13 * * *"]
